version: '3'
services:
  app:
    image: openjdk:17
    container_name: spring-app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: >
      sh -c "cd /app && ./mvnw spring-boot:run"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/interview_service
      - SPRING_DATASOURCE_USERNAME=gubee
      - SPRING_DATASOURCE_PASSWORD=gubee

  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=interview_service
      - POSTGRES_USER=gubee
      - POSTGRES_PASSWORD=gubee
